services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: wasm_exam
      POSTGRES_USER: wasm_exam
      POSTGRES_PASSWORD: wasm_exam
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
